Word2VecParams:
  vector_size: 256  # size of word embedding
  w2v_epochs: 4
  urls_hashtags_in_text: False

DatasetParams:
  apply_w2v: True   # Whether or not word2vec model will be used, so that each sample has at the end its associated
                    # text embedding. Must be true for CafayNet.

ModelParams:
  layer_width: 196
  num_layers: 4     # includes input and output layers (must be >= 2)
  dropout: 0.3      # dropout rate, 0.0 equivalent to no dropout

TrainingParams:
  num_splits: 10    # number of folds for cross validation
  split_seed: 12345 # seed for reproducibility of results